import numpy as np
import matplotlib.pyplot as plt
from cellpose import plot
import glob
import os
import pandas as pd
import matplotlib.gridspec as gridspec
import matplotlib.ticker as mticker
import matplotlib.lines as mlines
import numpy as np
from skimage import io as sk_io, color, measure  # Added measure for contour finding
from matplotlib import rc

import sys
import os
import Format_1 as F_1

import video_maker_1 as vm1

# Set up LaTeX font
rc('font', **{'family': 'serif', 'serif': ['Computer Modern Roman']})
rc('text', usetex=True)

@F_1.ParameterLog(max_size = 1024 * 10) # 10KB 
def plotter_2_CPvsA11_CST_zoom(input_dir, # Format_1 requires input_dir
    CP_data_df = None, # if None a .pkl file has to be in the input_dir. otherwise no CP_data data is provided.
    output_dir_manual = "", output_dir_comment = "CST_selected_zoom_expanded",
    video = 1,
    Plot_log_level=2, # Changed from 1 to 2
    ScaleFactor=1.5,
    cst_expansion_factor=6,  # Changed from 1 to 6
    image_numbers=[100],  # Changed from None to [100]
    cells_to_color=None,
    contour_color='w',
    contour_linestyle='-',
    contour_linewidth=1.0, # Changed from 0.8 to 1.0
    title_fontsize=18,     # Changed from 16 to 18
    axis_label_fontsize=14, # Changed from 12 to 14
    legend_fontsize=12,    # Changed from 10 to 12
    text_fontsize=12,      # Changed from 10 to 12
    suptitle_fontsize=20,  # Changed from 16 to 20
    num_bins = 20,         # Changed from 15 to 20
    show_training_diameter=False,  # Changed from True to False
    ):

    """
    Generates plots comparing Cellpose segmentation results (filtered by CST boundary) with A11 simulation data
    and optionally creates a video. This version zooms into the flame images.

    This function takes the data generated by `CP_extract_1` and processed by `CST_Selection_1`, or a pre-loaded DataFrame. 
    It loads various A11 simulation result files (e.g., mean radius, number of cells, iHRR)
    from fixed paths. For each image in the sequence, it creates a multi-panel plot:
    1. The original grayscale image (zoomed in to focus on the flame).
    2. The image overlaid with Cellpose outlines (zoomed).
    3. The image overlaid with Cellpose masks (zoomed).
    4. A horizontal histogram of detected cell diameters within CST boundary (non-dimensionalized)
       with mean and training diameters marked.
    5. A time-series plot comparing Cellpose-derived metrics (mean cell diameter,
       number of cells, CP efficiency) with corresponding A11 simulation data
       (mean flame radius, integral heat release rate) plotted against simulation time.

    Only cells selected by the CST (Cubed Sphere Tile) boundary are included in the metrics.
    The generated plots are saved as individual PNG files in the output directory.
    Optionally, these plots can be compiled into a video.

    Parameters
    ----------
    input_dir : str
        Path to the directory containing the `.pkl` file
        with data generated by `CST_Selection_1` or previous steps.
    CP_data_df : pandas.DataFrame or None, optional
        A pre-loaded DataFrame containing the segmentation data (including
        CST-filtered columns). If provided, it overrides loading from the
        `.pkl` file in `input_dir`. If None, the function attempts to load
        a .pkl file from `input_dir`. Defaults to None.
    output_dir_manual : str, optional
        If provided, specifies the exact output directory path for the plots/video.
        Overrides the default naming convention managed by `Format_1.F_out_dir`.
        Defaults to "".
    output_dir_comment : str, optional
        A comment to append to the default output directory name if `output_dir_manual`
        is not provided. Defaults to "".
    video : int, optional
        If 1, creates a video from the generated plot images using `video_maker_1.create_video_from_images`.
        If 0, only saves the individual plot images. Defaults to 1.
    Plot_log_level : int, optional
        Controls the verbosity of logging for this plotting function.
        Currently not implemented beyond accepting the parameter. Defaults to 1.
    ScaleFactor : float, optional
        Scale factor for zooming in on the spherical flame. Higher values = more zoom. Defaults to 1.5.
    cst_expansion_factor : int, optional
        Factor to multiply CST values by to compensate for partial sphere coverage.
        For example, set to 6 when CST covers 1/6 of the sphere to extrapolate 
        to full sphere statistics. Defaults to 1 (no expansion).
    image_numbers : list, optional
        List of image numbers to plot. If None or empty list [], all images are plotted.
        Default is None (plot all images).
    cells_to_color : list, optional
        List of cell IDs to color. If None or empty list [], all cells are colored.
    contour_color : str, optional
        Color of the cell outlines, by default 'w' (white)
    contour_linestyle : str, optional
        Line style of the cell outlines, by default '-' (solid)
    contour_linewidth : float, optional
        Line width of the cell outlines, by default 0.8
    title_fontsize : int, optional
        Font size for subplot titles, by default 16
    axis_label_fontsize : int, optional
        Font size for axis labels, by default 12
    legend_fontsize : int, optional
        Font size for legends, by default 10
    text_fontsize : int, optional
        Font size for text annotations, by default 10
    suptitle_fontsize : int, optional
        Font size for figure suptitle, by default 16
    num_bins : int, optional
        Number of bins for the histogram of cell diameters. Affects the resolution of the diameter distribution plot.
    show_training_diameter : bool, optional
        Whether to plot training diameter line on histogram and time series. Default is True.

    Returns
    -------
    output_dir : str
        The path to the directory where the output plots (and optionally video)
        are saved. This is always the first return value as required by Format_1.

    Notes
    -----
    - Relies on `Format_1.py` for output directory creation (`F_out_dir`) and
      parameter logging (`@F_1.ParameterLog`).
    - Requires CST-filtered data generated by `CST_Selection_1`.
    - Requires external data files containing A11 simulation results located at
      fixed paths (e.g., "C:\\Users\\obs\\OneDrive\\ETH\\ETH_MSc\\Masters Thesis\\Data\\A11_manual_extraction\\...").
    - Uses `video_maker_1.py` to create the video if `video=1`.
    - Assumes the input DataFrame contains specific CST columns generated by
      `CST_Selection_1`, including CST-filtered diameters, areas, etc.
    - The time-series plot uses multiple y-axes to display different quantities
      with varying scales (length, heat release rate, cell count, efficiency).
    """
    #################################################### I/O
    #
    output_dir = F_1.F_out_dir(input_dir, __file__, output_dir_comment = output_dir_comment, output_dir_manual = output_dir_manual) # Format_1 required definition of output directory


    #################################################### Load data

    pkl_files = glob.glob(os.path.join(input_dir, "*.pkl"))

    if pkl_files:
        CP_data_df_pkl = pkl_files[0] # If a .pkl file exists, use it as the pickle file path. If multiple .pkl files exist the first is used.
    else:
        CP_data_df_pkl = None

    if CP_data_df is None and CP_data_df_pkl is None:
        raise ValueError("No CP_data data provided. Provide Data.")
    elif CP_data_df is None and CP_data_df_pkl is not None:
        print(f"Loading CP_data data from pickle file {os.path.basename(CP_data_df_pkl)}")
        CP_data_df = pd.read_pickle(CP_data_df_pkl)
    elif CP_data_df is not None and CP_data_df_pkl is None:
        print("Loading CP_data data from passed DataFrame in function argument")
        # No action needed since CP_data_df is already passed
    elif CP_data_df is not None and CP_data_df_pkl is not None:
        print("Both CP_data_df and CP_data_df_pkl provided. Using data from passed DataFrame in function argument")
        # No action needed since CP_data_df is already passed
    else:
        raise ValueError("Loading CP_data data disambiguation failed. Check CP_data_df and CP_data_df_pkl")
    
    # Check if CST columns exist
    if 'd_cell_distribution_CST_nonDim' not in CP_data_df.columns:
        raise ValueError("DataFrame is missing required CST columns. Run CST_Selection_1 first.")

    if 'Time_VisIt' in CP_data_df.columns and CP_data_df['Time_VisIt'] is not None:
        print("Time_VisIt column found in CP_data_df. Using it as time.")
        CP_data_df['time'] = CP_data_df['Time_VisIt']
    else: 
        print("No Time_VisIt column found in CP_data_df. Using index as time.")
        CP_data_df['time'] = CP_data_df.index

    # Load A11 data
    # Define the file paths
    file_paths = [
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_K_mean_as_mean_stretch_rate_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_N_c_as_number_of_cells_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_R_mean_as_average_radius_of_the_wrinkled_flame_fron_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_R_mean_dot_as_first_time_derivative_of_the_average_radius_of_the_wrinkled_flame_front_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_s_a_as_average_normal_component_of_the_absolute_propagation_velocity_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_s_d_as_average_density_weighted_displacement_speed_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_A_as_flame_surface_area_of_the_wrinkled_spherical_front_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_a_t_as_average_total_aerodynamic_strain_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_iHRR_as_integral_heat_release_rate_vs_time_manual_extraction.txt",
        r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_K_geom_as_geometric_stretch_rate_vs_time_manual_extraction.txt"
    ]

    # Load all files into a dictionary of DataFrames and create variables dynamically
    for file_path in file_paths:
        # Extract file name without path and extension
        file_name = file_path.split('\\')[-1].replace('.txt', '')
        
        # Simplify the variable name by removing 'A11_SF_' and '_as' parts
        variable_name = file_name.split('_as')[0]
        
        # Load the CSV file into a DataFrame and assign it dynamically
        globals()[variable_name] = pd.read_csv(file_path)
        
        ''' A11 dataframes:
        A11_SF_K_mean
        A11_SF_N_c
        A11_SF_R_mean
        A11_SF_R_mean_dot
        A11_SF_s_a
        A11_SF_s_d
        A11_SF_A
        A11_SF_a_t
        A11_SF_iHRR
        A11_SF_K_geom
        '''

    #################################################### Plotting

    # Calculate mean and cell count for CST data
    CP_data_df['d_cell_CST_mean_nonDim'] = CP_data_df['d_cell_distribution_CST_nonDim'].apply(
        lambda x: np.mean(x) if x.size > 0 else np.nan)
    
    # Apply the expansion factor to the CST cell count
    CP_data_df['N_cells_CST'] = CP_data_df['d_cell_distribution_CST_nonDim'].apply(
        lambda x: len(x) if hasattr(x, '__len__') else 0) * cst_expansion_factor
    
    CP_data_df['A_cell_CST_sum_nonDim2'] = CP_data_df['A_cell_distribution_CST_nonDim2'].apply(
        lambda x: np.sum(x) if x.size > 0 else 0) * cst_expansion_factor
    
    # Number of rows in the DataFrame
    N_images = len(CP_data_df)

    # Find the maximum frequency for all CST histograms
    max_diameter_row = CP_data_df['d_cell_distribution_CST_nonDim'].apply(
        lambda x: np.max(x) if (hasattr(x, 'size') and x.size > 0) else None)
    max_diameter = max_diameter_row.max() if not pd.isna(max_diameter_row.max()) else 0
    bin_size = max_diameter/num_bins if max_diameter > 0 else 0.1
    max_frequency = 0
    
    for i in range(N_images):
        if hasattr(CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'], 'size') and CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'].size > 0:
            unique_diameters, counts_diameters = np.unique(CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'], return_counts=True)
            max_diameter_i = max(unique_diameters) if unique_diameters.size > 0 else 0
            if max_diameter_i > 0:
                bins = np.arange(0, max_diameter_i + bin_size, bin_size)    
                hist, _ = np.histogram(CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'], bins=bins)
                if hist.size > 0:
                    max_frequency = max(max_frequency, hist.max())
    
    print(f"\nPlotting data for image:")
    
    # If no image numbers provided, use all images
    if image_numbers is None or len(image_numbers) == 0:
        images_to_process = range(N_images)
    else:
        # Find indices for the requested image numbers
        images_to_process = []
        for idx, row in CP_data_df.iterrows():
            if row['image_number'] in image_numbers:
                images_to_process.append(idx)

    # Plot the selected images 
    for i in images_to_process:
        print(f"\r{os.path.basename(CP_data_df.loc[i, 'image_file_path'])} \t {i+1}/{N_images}", end='', flush=True)

        # Create the figure with a custom GridSpec layout
        fig = plt.figure(figsize=(15, 10))
        gs = gridspec.GridSpec(2, 3, figure=fig)

        # Get the image, outlines, and masks for the current row
        original_img = sk_io.imread(CP_data_df.loc[i, 'image_file_path'])[..., :3]  # Read as RGB
        image = color.rgb2gray(original_img)  # Convert to grayscale
        outlines = CP_data_df.loc[i, 'outlines']
        masks = CP_data_df.loc[i, 'masks']
        
        # Apply zooming, similar to plot6_colortables.py
        D_SF_px = CP_data_df.loc[i, 'D_SF_px']
        if D_SF_px > 0:
            # Calculate zoom region to focus on the spherical flame
            img_height, img_width = original_img.shape[:2]
            center_x, center_y = img_width // 2, img_height // 2
            zoom_half_size = int(D_SF_px * ScaleFactor / 2)
            
            # Ensure zoom region is within image bounds
            left = max(0, center_x - zoom_half_size)
            right = min(img_width, center_x + zoom_half_size)
            top = max(0, center_y - zoom_half_size)
            bottom = min(img_height, center_y + zoom_half_size)
            
            # Extract the zoom regions
            zoomed_image = image[top:bottom, left:right]
            zoomed_original = original_img[top:bottom, left:right]
            zoomed_outlines = outlines[top:bottom, left:right] if outlines is not None else None
            zoomed_masks = masks[top:bottom, left:right] if masks is not None else None
        else:
            # If no flame diameter info, don't zoom
            zoomed_image = image
            zoomed_original = original_img
            zoomed_outlines = outlines
            zoomed_masks = masks

        # plot panel
        ax_0_0 = fig.add_subplot(gs[0, 0])
        ax_0_1 = fig.add_subplot(gs[0, 1])
        ax_0_2 = fig.add_subplot(gs[0, 2])
        ax_1_0 = fig.add_subplot(gs[1, 0])
        ax_1_12 = fig.add_subplot(gs[1, 1:3]) # spanning across two columns

        # Plot: original zoomed image
        ax_0_0.imshow(zoomed_image, cmap='gray')
        ax_0_0.set_title(f"Original Image (Zoomed) at $\\tau={CP_data_df.iloc[i]['time']:.2f}$", 
                       fontsize=title_fontsize)
        ax_0_0.axis('off')
        
        # Plot: zoomed image with outlines using custom outlines like plot13
        ax_0_1.imshow(zoomed_image, cmap='gray', alpha=1)  # First overlay of original image
        
        # Draw outlines manually like in plot13_segmented_image
        if zoomed_masks is not None:
            # Get unique cell IDs (excluding background)
            unique_cells = np.unique(zoomed_masks)
            unique_cells = unique_cells[unique_cells > 0]
            
            for cell_id in unique_cells:
                # Skip cells not in cells_to_color if it's specified
                if cells_to_color is not None and len(cells_to_color) > 0:
                    if cell_id not in cells_to_color:
                        continue
                        
                cell_mask = zoomed_masks == cell_id
                contours = measure.find_contours(cell_mask, 0.5)
                
                for contour in contours:
                    ax_0_1.plot(contour[:, 1], contour[:, 0], 
                               color=contour_color, 
                               linestyle=contour_linestyle, 
                               linewidth=contour_linewidth)
                               
        ax_0_1.set_title(r"Cell Outlines", fontsize=title_fontsize)
        ax_0_1.axis('off')
        
        # Plot: zoomed image with masks
        ax_0_2.imshow(zoomed_image, cmap='gray')
        if zoomed_masks is not None:
            ax_0_2.imshow(plot.mask_overlay(zoomed_image, zoomed_masks), alpha=0.5, cmap='gist_rainbow')
        # Update title to include expansion factor if > 1
        ax_0_2.set_title(r"Cell Masks", fontsize=title_fontsize)
        ax_0_2.axis('off')

        # Plot: CST Diameter distribution vs. diameter frequency (bin count histogram)
        # Check if we have CST diameter data
        has_cst_data = (hasattr(CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'], 'size') and
                        CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'].size > 0)
        
        if has_cst_data:
            unique_diameters, counts_diameters = np.unique(CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'], return_counts=True)
            max_diameter_i = max(unique_diameters) if unique_diameters.size > 0 else 0
            bins = np.arange(0, max_diameter_i + bin_size, bin_size)

            ax_1_0.hist(CP_data_df.loc[i, 'd_cell_distribution_CST_nonDim'], bins=bins, 
                       orientation='horizontal', edgecolor='turquoise', color='white', linewidth=2)
        
        ax_1_0.set_title(r"Diameter Distribution", fontsize=title_fontsize)
        ax_1_0.set_xlabel(r"Frequency", fontsize=axis_label_fontsize)
        ax_1_0.set_ylabel(r"Diameter/$\delta_T$", fontsize=axis_label_fontsize)
        ax_1_0.set_xlim(0, max_frequency*1.05 if max_frequency > 0 else 1)
        
        # Set y-limit based on available data
        max_diam_limit = CP_data_df['d_cell_distribution_CST_nonDim'].apply(
            lambda x: np.max(x) if (hasattr(x, 'size') and x.size > 0) else 0).max() * 1.05
        ax_1_0.set_ylim(0, max_diam_limit if max_diam_limit > 0 else 1)

        # Add mean and training diameter lines
        if has_cst_data and pd.notna(CP_data_df.loc[i, 'd_cell_CST_mean_nonDim']):
            mean_diameter = CP_data_df.loc[i, 'd_cell_CST_mean_nonDim']
            ax_1_0.axhline(mean_diameter, color='green', linewidth=2)
            ax_1_0.text(ax_1_0.get_xlim()[1] * 0.5, mean_diameter + max_diam_limit*0.01, 
                      r'Mean: ${:.2f}$'.format(mean_diameter), color='green',
                      fontsize=text_fontsize)
        
        # Only plot training diameter if show_training_diameter is True
        if show_training_diameter and pd.notna(CP_data_df.iloc[i]['diameter_training_nonDim']):
            diameter_training_nonDim = CP_data_df.iloc[i]['diameter_training_nonDim']
            ax_1_0.axhline(diameter_training_nonDim, color='violet', linewidth=1)
            ax_1_0.text(ax_1_0.get_xlim()[1] * 0.6, diameter_training_nonDim + max_diam_limit*0.01, 
                      r'Training: ${:.2f}$'.format(diameter_training_nonDim), color='violet',
                      fontsize=text_fontsize)

        # Plot: Time-series plot with CST values
        if 'd_cell_CST_mean_nonDim' in CP_data_df.columns:
            line_1_12_1, = ax_1_12.plot(CP_data_df['time'], CP_data_df['d_cell_CST_mean_nonDim'], 
                                     label=f"{CP_data_df.iloc[i]['d_cell_CST_mean_nonDim']:05.2f}" + 
                                     r" = Cell Mean Diameter/$\delta_T$", color='green')
        else:
            line_1_12_1, = ax_1_12.plot([], [], label="CST Cell Mean Diameter not available", color='green')
            
        # Only plot training diameter line in time series if show_training_diameter is True
        if show_training_diameter:
            line_1_12_2, = ax_1_12.plot(CP_data_df['time'], CP_data_df['diameter_training_nonDim'], 
                                     label=f"{CP_data_df.iloc[i]['diameter_training_nonDim'] if pd.notna(CP_data_df.iloc[i]['diameter_training_nonDim']) else 0.00:05.2f} = Cellpose Training Diameter/$\\delta_T$", 
                                     color='violet')
        else:
            # Create a placeholder for the legend to maintain consistency in handle indices
            line_1_12_2, = ax_1_12.plot([], [], color='none')
            line_1_12_2.set_visible(False)
        
        # Get time of current frame
        cp_time = CP_data_df.iloc[i]['time']
        
        # Get A11 data at current time
        closest_index_R_mean = (np.abs(A11_SF_R_mean['time'] - cp_time)).argmin()
        closest_index_iHRR = (np.abs(A11_SF_iHRR['time'] - cp_time)).argmin()
        
        # Get A11 values if in range
        if (A11_SF_R_mean['time'].iloc[closest_index_R_mean] >= A11_SF_R_mean['time'].min() and 
            A11_SF_R_mean['time'].iloc[closest_index_R_mean] <= A11_SF_R_mean['time'].max()):
            closest_A11_r_mean = A11_SF_R_mean['R_mean'].iloc[closest_index_R_mean]
        else:
            closest_A11_r_mean = np.nan
            
        if (A11_SF_iHRR['time'].iloc[closest_index_iHRR] >= A11_SF_iHRR['time'].min() and 
            A11_SF_iHRR['time'].iloc[closest_index_iHRR] <= A11_SF_iHRR['time'].max()):
            closest_A11_iHRR = A11_SF_iHRR['iHRR'].iloc[closest_index_iHRR]
        else:
            closest_A11_iHRR = np.nan
        
        # Plot A11 data and CST data
        S2 = 1e-3
        line_1_12_3, = ax_1_12.plot(A11_SF_R_mean['time'], A11_SF_R_mean['R_mean'] *2 * S2, 
                                  label=f"{(closest_A11_r_mean*S2):05.2f} = Spherical Flame Diameter/$\\delta_T$ * {S2:.3f}", 
                                  color='olive', linestyle='dashed')

        S3 = 1
        ax_1_12_L = ax_1_12.twinx()
        line_1_12_L, = ax_1_12_L.plot(A11_SF_iHRR['time'], A11_SF_iHRR['iHRR'] * S3, 
                                     label=f"{(closest_A11_iHRR*S2):05.2f} = Integral Heat Release Rate * {S2:.3f}", 
                                     color='orange', linestyle='dashed')

        # Add CST cell count
        ax_1_12_R = ax_1_12.twinx()
        line_1_12_R, = ax_1_12_R.plot(CP_data_df['time'], CP_data_df['N_cells_CST'], 
                                    label=f"{CP_data_df.iloc[i]['N_cells_CST']:.0f} = Number of cells" + 
                                          (f" × {cst_expansion_factor}" if cst_expansion_factor > 1 else ""), 
                                    color='red')

        # Mark current image time
        line_1_12_4 = ax_1_12.axvline(CP_data_df.iloc[i]['time'], color='black', 
                                    label=f"{CP_data_df.iloc[i]['time']:.2f} = Time $\\tau$", 
                                    linestyle='dashed', linewidth=3)

        # Set the limits and labels for the axes
        ax_1_12.set_xlim(0, 7)
        
        if max_diam_limit > 0:
            ax_1_12.set_ylim(0, max_diam_limit)
        else:
            ax_1_12.set_ylim(0, 1)
            
        ax_1_12_L.set_ylim(0, A11_SF_iHRR['iHRR'].max()*1.05)
        
        n_cells_min = CP_data_df['N_cells_CST'].min() if not pd.isna(CP_data_df['N_cells_CST'].min()) else 0
        n_cells_max = CP_data_df['N_cells_CST'].max() if not pd.isna(CP_data_df['N_cells_CST'].max()) else 1
        ax_1_12_R.set_ylim(n_cells_min, n_cells_max*1.05)
        

        ax_1_12.set_xlabel(r"Time $\tau$", fontsize=axis_label_fontsize)
        ax_1_12.set_ylabel(r"Diameter/$\delta_T$", color='green', fontsize=axis_label_fontsize)
        ax_1_12_L.set_ylabel(r"Integral Heat Release Rate", color='orange', fontsize=axis_label_fontsize)
        ax_1_12_R.set_ylabel(r"Number of Cells", color='red', fontsize=axis_label_fontsize)
        
        # order legend
        handles = [
            line_1_12_4, # Image number
            line_1_12_1, # CST mean diameter
        ]
        labels = [
            line_1_12_4.get_label(), # Image number
            line_1_12_1.get_label(), # CST mean diameter
        ]
        
        # Only include training diameter in legend if show_training_diameter is True
        if show_training_diameter:
            handles.append(line_1_12_2)  # training diameter
            labels.append(line_1_12_2.get_label())  # training diameter
            
        handles.append(line_1_12_3)  # A11 R_mean
        labels.append(line_1_12_3.get_label())  # A11 R_mean
        
        ax_1_12.legend(handles, labels, loc='upper left', fontsize=legend_fontsize, frameon=False)
        
        solid_line = mlines.Line2D([], [], color='black', linestyle='-', label="Cellpose (CST)")
        dashed_line = mlines.Line2D([], [], color='black', linestyle='--', label="Altantzis 2011")
        handles_title = [dashed_line, solid_line]
        labels_title = [dashed_line.get_label(), solid_line.get_label()]

        fig_legend = ax_1_12.get_figure()
        fig_legend.legend(handles_title, labels_title, loc='upper center', 
                          fontsize=legend_fontsize, frameon=False, ncol=2, 
                          bbox_to_anchor=(0.5, 1.05))

        ax_1_12_L.spines["right"].set_position(("outward", 0))  # Slightly to the right
        ax_1_12_L.yaxis.set_label_position("right")
        ax_1_12_L.yaxis.set_ticks_position("right")

        ax_1_12_R.tick_params(axis='y', labelcolor='red')
        ax_1_12_R.spines["right"].set_color('red')
        ax_1_12_R.spines["right"].set_position(("outward", 45))  # Move further right
        ax_1_12_R.yaxis.set_label_position("right")
        ax_1_12_R.yaxis.set_ticks_position("right")


        ax_1_12_L.tick_params(axis='y', labelcolor='orange')
        ax_1_12_L.spines["right"].set_color('orange')
        ax_1_12_L.yaxis.set_major_formatter(mticker.ScalarFormatter(useMathText=True))
        ax_1_12_L.ticklabel_format(style='sci', axis='y', scilimits=(0, 0))
        offset_text = ax_1_12_L.yaxis.get_offset_text()
        offset_text.set_position((1.05, 1))  # Move to the right and above the axis

        # Add a title indicating this is CST data with zooming and expansion factor
        plt.suptitle(r"Altantzis SF Cell Analysis", fontsize=suptitle_fontsize, y=0.98)

        # Adjust layout and save the figure as a PNG file
        plt.tight_layout(rect=[0, 0, 1, 0.95])  # Make room for the suptitle
        plot_filename = os.path.join(output_dir, f'plot_CST_zoom_{i:04d}.png')
        plt.savefig(plot_filename)
        plt.close(fig)
    print("\n") # new line

    if video == 1:
        vm1.create_video_from_images(
            plot_image_folder = output_dir,
            video_output_dir = output_dir, 
            fps=5,
            output_dir_comment="CST_analysis_zoom"  # Changed from video_name to output_dir_comment
        )
    
    #################################################### return
    
    print(f"Plotter 2 Zoom (CPvsA11_CST_zoom) finished. Output in {output_dir}")
    return output_dir # Format_1 requires output_dir as first return

# Example usage when script is run directly
if __name__ == "__main__":
    print("Running plotter_2_CPvsA11_CST_zoom as standalone module...")
    
    # Get input directory from user
    input_dir = r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\CIPS_Pipe_Default_dir\20250625_1528537\20250625_1528554\20250625_1626096\20250626_1700136\20250626_1706361"
    
    # Run the plotter function
    output_dir = plotter_2_CPvsA11_CST_zoom(
        input_dir=input_dir,
        video=1,
        Plot_log_level=2,
        ScaleFactor=1.5,  # Adjust zoom level - higher values zoom in more
        cst_expansion_factor=6,  # Added expansion factor to extrapolate to full sphere
        image_numbers=[100],  # Only process these specific image numbers, use [] for all images
        cells_to_color=None,  # Only color specific cells (use None or [] for all cells)
        contour_color='w',  # White outlines
        contour_linestyle='-',  # Solid line
        contour_linewidth=1.0,  # Line width for outlines
        title_fontsize=18,     # Larger title font size
        axis_label_fontsize=14, # Larger axis label font size 
        legend_fontsize=12,    # Larger legend font size
        text_fontsize=12,      # Larger text annotation font size
        suptitle_fontsize=20,  # Larger suptitle font size
        output_dir_comment="CST_selected_zoom_expanded",
        num_bins = 20,
        show_training_diameter=False,  # Hide training diameter
    )
    
    print(f"\nAnalysis complete! Results saved to: {output_dir}")
