import matplotlib.pyplot as plt
import numpy as np
import glob
import os
import pandas as pd
import matplotlib.gridspec as gridspec
import matplotlib.ticker as mticker
import matplotlib.lines as mlines
plt.rcParams['text.usetex'] = False  # Keep False unless you have a full LaTeX installation

import sys
import os
import Format_1 as F_1

import video_maker_1 as vm1


@F_1.ParameterLog(max_size = 1024 * 10) # 10KB 
def plotter_3_CPvsA11_CST_Panel(input_dir, # Format_1 requires input_dir
    CP_data_df = None, # if None a .pkl file has to be in the input_dir. otherwise no CP_data data is provided.
    output_dir_manual = "", output_dir_comment = "",
    cst_expansion_factor = 1, # Factor to multiply CST values by (e.g. 6 for extrapolating from 1/6 of the sphere)
    show_plot = 0,
    Plot_log_level=1, # Added Plot_log_level argument
    ):

    """
    Generates a panel plot comparing Cellpose CST-selected results with A11 simulation data.

    This function loads Cellpose extraction data processed by CST_Selection_1 and A11
    simulation data. It generates a 5x2 panel figure comparing various A11 metrics
    (left column) against CST-filtered Cellpose metrics (right column, plotted on twin axes).
    Metrics include flame area, iHRR, mean radius, radius time derivative,
    cell count, stretch rates, strain, propagation speeds, and the
    dimensionalization factor d_T/px.

    Parameters
    ----------
    input_dir : str
        Path to the directory containing the `.pkl` file
        with data generated by `CST_Selection_1`.
    CP_data_df : pandas.DataFrame or None, optional
        A pre-loaded DataFrame containing the segmentation data with CST columns. 
        Overrides loading from the `.pkl` file if provided. Defaults to None.
    output_dir_manual : str, optional
        Manual path for the output directory. Overrides default naming. Defaults to "".
    output_dir_comment : str, optional
        Comment appended to the default output directory name. Defaults to "".
    cst_expansion_factor : int, optional
        Factor to multiply CST values by to compensate for partial sphere coverage.
        For example, set to 6 when CST covers 1/6 of the sphere to extrapolate 
        to full sphere statistics. Defaults to 1 (no expansion).
    show_plot : int, optional
        If 1, displays the generated panel plot using `plt.show()`. Defaults to 0.
    Plot_log_level : int, optional
        Controls the verbosity of logging for this plotting function.
        Currently not implemented beyond accepting the parameter. Defaults to 1.

    Returns
    -------
    output_dir : str
        The path to the directory where the output plots are saved.

    Notes
    -----
    - Relies on `Format_1.py` for output directory creation and logging.
    - Requires external A11 data files at fixed paths.
    - Requires CST-filtered data generated by `CST_Selection_1`.
    - Uses Matplotlib's GridSpec for complex panel layouts.
    - The panel plot is saved as `plot_panel_CST.png`.
    """
    #################################################### I/O
    #
    output_dir = F_1.F_out_dir(input_dir, __file__, output_dir_comment = output_dir_comment, output_dir_manual = output_dir_manual) # Format_1 required definition of output directory


    #################################################### Load CP extract data
    pkl_files = glob.glob(os.path.join(input_dir, "*.pkl"))

    if pkl_files:
        CP_data_df_pkl = pkl_files[0] # If a .pkl file exists, use it as the pickle file path. If multiple .pkl files exist the first is used.
    else:
        CP_data_df_pkl = None

    if CP_data_df is None and CP_data_df_pkl is None:
        raise ValueError("No CP_data data provided. Provide Data.")
    elif CP_data_df is None and CP_data_df_pkl is not None:
        print(f"Loading CP_data data from pickle file {os.path.basename(CP_data_df_pkl)}")
        CP_data_df = pd.read_pickle(CP_data_df_pkl)
    elif CP_data_df is not None and CP_data_df_pkl is None:
        print("Loading CP_data data from passed DataFrame in function argument")
        # No action needed since CP_data_df is already passed
    elif CP_data_df is not None and CP_data_df_pkl is not None:
        print("Both CP_data_df and CP_data_df_pkl provided. Using data from passed DataFrame in function argument")
        # No action needed since CP_data_df is already passed
    else:
        raise ValueError("Loading CP_data data disambiguation failed. Check CP_data_df and CP_data_df_pkl")

    # Check if CST columns exist in the dataframe
    if 'd_cell_distribution_CST_nonDim' not in CP_data_df.columns:
        raise ValueError("DataFrame is missing required CST columns. Run CST_Selection_1 first.")

    if 'Time_VisIt' in CP_data_df.columns and CP_data_df['Time_VisIt'] is not None:
        print("Time_VisIt column found in CP_data_df. Using it as time.")
        CP_data_df['time'] = CP_data_df['Time_VisIt']
    else: 
        print("No Time_VisIt column found in CP_data_df. Using index as time.")
        CP_data_df['time'] = CP_data_df.index


    # Load A11 data
    A11_SF_K_mean = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_K_mean_as_mean_stretch_rate_vs_time_manual_extraction.txt")
    A11_SF_N_c = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_N_c_as_number_of_cells_vs_time_manual_extraction.txt")
    A11_SF_R_mean = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_R_mean_as_average_radius_of_the_wrinkled_flame_fron_vs_time_manual_extraction.txt")
    A11_SF_R_mean_dot = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_R_mean_dot_as_first_time_derivative_of_the_average_radius_of_the_wrinkled_flame_front_vs_time_manual_extraction.txt")
    A11_SF_s_a = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_s_a_as_average_normal_component_of_the_absolute_propagation_velocity_vs_time_manual_extraction.txt")
    A11_SF_s_d = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_s_d_as_average_density_weighted_displacement_speed_vs_time_manual_extraction.txt")
    A11_SF_A = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_A_as_flame_surface_area_of_the_wrinkled_spherical_front_vs_time_manual_extraction.txt")
    A11_SF_a_t = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_a_t_as_average_total_aerodynamic_strain_vs_time_manual_extraction.txt")
    A11_SF_iHRR = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_iHRR_as_integral_heat_release_rate_vs_time_manual_extraction.txt")
    A11_SF_K_geom = pd.read_csv(r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\Data\A11_manual_extraction\A11_SF_K_geom_as_geometric_stretch_rate_vs_time_manual_extraction.txt")


    #################################################### Compute CST Statistics

    # Calculate mean and cell count for CST data
    CP_data_df['d_cell_CST_mean_nonDim'] = CP_data_df['d_cell_distribution_CST_nonDim'].apply(
        lambda x: np.mean(x) if (hasattr(x, 'size') and x.size > 0) else np.nan)
    
    # Apply the expansion factor to the CST cell count
    CP_data_df['N_cells_CST'] = CP_data_df['d_cell_distribution_CST_nonDim'].apply(
        lambda x: len(x) if hasattr(x, '__len__') else 0) * cst_expansion_factor
    
    CP_data_df['A_cell_CST_sum_nonDim2'] = CP_data_df['A_cell_distribution_CST_nonDim2'].apply(
        lambda x: np.sum(x) if (hasattr(x, 'size') and x.size > 0) else 0) * cst_expansion_factor
    
    # Find the maximum frequency for all CST histograms
    max_diameter_row = CP_data_df['d_cell_distribution_CST_nonDim'].apply(
        lambda x: np.max(x) if (hasattr(x, 'size') and x.size > 0) else None)
    max_diameter = max_diameter_row.max() if not pd.isna(max_diameter_row.max()) else 0

    # Number of rows in the DataFrame
    N_images = len(CP_data_df)
    
    print(f"\nPlotting CST Panel with expansion factor {cst_expansion_factor}...")

    #################################################### Plotting Panel 4 (CST Version)

    # Create the figure with a custom GridSpec layout
    fig = plt.figure(figsize=(15, 15))
    gs = gridspec.GridSpec(5, 2, figure=fig, height_ratios=[1, 1, 1, 1, 1])
    gs.update(hspace=0)  # Remove gaps

    solid_line = mlines.Line2D([], [], color='black', linestyle='-', label="Cellpose (CST)")
    dashed_line = mlines.Line2D([], [], color='black', linestyle='--', label="Altantzis 2011")

    title = f"CST Analysis Panel (Expansion Factor: {cst_expansion_factor})"
    fig.suptitle(title, fontsize=20, fontweight='bold', y=1.02)  # Adjust y for spacing
    fig.legend(handles=[dashed_line, solid_line], loc='upper center', fontsize=12, frameon=False, ncol=2)

    # Create left column subplots with shared x-axis
    ax_0_0 = fig.add_subplot(gs[0, 0])
    ax_1_0 = fig.add_subplot(gs[1, 0], sharex=ax_0_0)
    ax_2_0 = fig.add_subplot(gs[2, 0], sharex=ax_0_0)
    ax_3_0 = fig.add_subplot(gs[3, 0], sharex=ax_0_0)
    ax_4_0 = fig.add_subplot(gs[4, 0], sharex=ax_0_0)
    # Create right column subplots with shared x-axis
    ax_0_1 = fig.add_subplot(gs[0, 1])
    ax_1_1 = fig.add_subplot(gs[1, 1], sharex=ax_0_1)
    ax_2_1 = fig.add_subplot(gs[2, 1], sharex=ax_0_1)
    ax_3_1 = fig.add_subplot(gs[3, 1], sharex=ax_0_1)
    ax_4_1 = fig.add_subplot(gs[4, 1], sharex=ax_0_1)

    # A11 first plot column
    ax_0_0.plot(A11_SF_A['time'], A11_SF_A['A'] ,
                label="A11 Spherical Flame Area $A_{SF}$", color='black', linestyle='dashed')
    ax_0_0.set_ylim(0, A11_SF_A['A'].max()*1.05)
    ax_0_0.tick_params(axis='y', labelcolor='black')
    ax_0_0.spines["left"].set_color('black')
    ax_0_0.yaxis.set_major_formatter(mticker.ScalarFormatter(useMathText=True))
    ax_0_0.ticklabel_format(style='sci', axis='y', scilimits=(0, 0))
    offset_text = ax_0_0.yaxis.get_offset_text()
    offset_text.set_position((0, 1))  # Move to the right and above the axis
    ax_0_0.set_ylabel("A11 Spherical Flame Area $A_{SF}$", color='black')

    ax_1_0.plot(A11_SF_iHRR['time'], A11_SF_iHRR['iHRR'],
                label="A11 Integral heat release rate $iHRR$", color='black', linestyle='dashed')
    ax_1_0.set_ylim(0, A11_SF_iHRR['iHRR'].max()*1.05)
    ax_1_0.tick_params(axis='y', labelcolor='black')
    ax_1_0.spines["left"].set_color('black')
    ax_1_0.yaxis.set_major_formatter(mticker.ScalarFormatter(useMathText=True))
    ax_1_0.ticklabel_format(style='sci', axis='y', scilimits=(0, 0))
    offset_text = ax_1_0.yaxis.get_offset_text()
    offset_text.set_position((-0.5, -0.5))  # Move offset text to the left side (x=-0.1)
    ax_1_0.set_ylabel("A11 Integral Heat Release Rate $iHRR$", color='black')

    ax_2_0.plot(A11_SF_R_mean['time'], A11_SF_R_mean['R_mean'] ,
                label="A11 Spherical Flame Radius $R_{mean}$", color='black', linestyle='dashed')
    ax_2_0.set_ylabel("A11 Spherical Flame Radius $R_{mean}$", color='black')
    ax_2_0.tick_params(axis='y', labelcolor='black')

    ax_3_0.plot(A11_SF_R_mean_dot['time'], A11_SF_R_mean_dot['R_mean_dot'] ,
                label="A11 Spherical Flame Radius first \ntime derivative $\dot{R}_{\text{mean}}$", color='black', linestyle='dashed')
    ax_3_0.set_ylabel("A11 Spherical Flame Radius first \ntime derivative $\dot{R}_{\text{mean}}$", color='black')
    ax_3_0.tick_params(axis='y', labelcolor='black')

    ax_4_0.plot(A11_SF_N_c['time'], A11_SF_N_c['N_c'] ,
                label="A11 Number of cells $N_c$", color='black', linestyle='dashed')
    ax_4_0.set_ylabel("A11 Number of cells $N_c$", color='black')
    ax_4_0.tick_params(axis='y', labelcolor='black')

    # A11 second plot column
    ax_0_1.plot(A11_SF_K_geom['time'], A11_SF_K_geom['K_geom'] ,
                label="A11 geometric stretch rate $K_{geom}$", color='black', linestyle='dashed')
    ax_0_1.plot(A11_SF_K_mean['time'], A11_SF_K_mean['K_mean'] ,
                label="A11 mean stretch rate $K_{mean}$", color='blue', linestyle='dashed')

    ax_1_1.plot(A11_SF_a_t['time'], A11_SF_a_t['a_t'] ,
                label="A11 average total areodynamic strain $a_t$", color='black', linestyle='dashed')

    ax_2_1.plot(A11_SF_s_a['time'], A11_SF_s_a['s_a'] ,
                label="A11 average normal absolute propagation velocity $s_a$", color='black', linestyle='dashed')

    ax_3_1.plot(A11_SF_s_d['time'], A11_SF_s_d['s_d'] ,
                label="A11 average density weighed displacement speed $s_d$", color='black', linestyle='dashed')

    ax_4_1.plot(CP_data_df['time'], CP_data_df['d_T_per_px'] ,
                label="Dimentionalisation $d_T/px$", color='black', linestyle='dotted')

    axes = [
        ax_0_0, ax_1_0, ax_2_0, ax_3_0, ax_4_0,
        ax_0_1, ax_1_1, ax_2_1, ax_3_1, ax_4_1
    ]
    axes_L = [
        ax_0_0, ax_1_0, ax_2_0, ax_3_0, ax_4_0
    ]
    axes_R = [
        ax_0_1, ax_1_1, ax_2_1, ax_3_1, ax_4_1
    ]

    # Create a list to store references to the green twin axes
    green_axes = []
    
    # Loop through each subplot and apply the plots
    for i, ax in enumerate(axes_R):
        # Add Twin Axes
        ax_R1 = ax.twinx()
        # Store reference to green axis
        green_axes.append(ax_R1)
        
        ax_R1.plot(CP_data_df['time'], CP_data_df['d_cell_CST_mean_nonDim'],
                    label="CST Cell Mean Diameter $D_{c,mean}$", color='green')
        ax_R1.set_ylabel("CST Cell Mean Diameter $ D_{c,mean}$", color='green')
        
        # Format tick labels consistently with 3 decimal places
        ax_R1.yaxis.set_major_formatter(mticker.FormatStrFormatter('%.3f'))
        
        ax_R2 = ax.twinx()
        ax_R2.plot(CP_data_df['time'], CP_data_df['N_cells_CST'],
                    label=f"CST Cell Count × {cst_expansion_factor}" if cst_expansion_factor > 1 else "CST Cell Count",
                    color='red')
        ax_R2.set_ylabel(f"CST Cell Count × {cst_expansion_factor}" if cst_expansion_factor > 1 else "CST Cell Count", color='red')


        # Set Limits
        ax_R1.set_ylim(0, max_diameter * 1.05)
        ax_R2.set_ylim(CP_data_df['N_cells_CST'].min(), CP_data_df['N_cells_CST'].max() * 1.05)

        # Adjust Twin Axes Positions with increased spacing
        ax_R1.spines["right"].set_position(("outward", 0))
        ax_R2.spines["right"].set_position(("outward", 60))  # Increased from 40 to 60

        ax_R1.spines["right"].set_color('green')
        ax_R2.spines["right"].set_color('red')

        ax_R1.tick_params(axis='y', labelcolor='green')
        ax_R2.tick_params(axis='y', labelcolor='red')

        ax.set_xlim(0, 7)

    for ax in axes_L:
        # Add Twin Axes
        ax_R1 = ax.twinx()
        ax_R1.plot(CP_data_df['time'], CP_data_df['d_cell_CST_mean_nonDim'],
                    label="CST Cell Mean Diameter $D_{c,mean}$", color='green')

        ax_R2 = ax.twinx()
        ax_R2.plot(CP_data_df['time'], CP_data_df['N_cells_CST'],
                    label=f"CST Cell Count × {cst_expansion_factor}" if cst_expansion_factor > 1 else "CST Cell Count", 
                    color='red')


        # Set Limits
        ax_R1.set_ylim(0, max_diameter * 1.05)
        ax_R2.set_ylim(CP_data_df['N_cells_CST'].min(), CP_data_df['N_cells_CST'].max() * 1.05)

        # Turn off all ticks and tick labels for the twin y-axes
        ax_R1.tick_params(axis='both', which='both', length=0)  # Hide ticks
        ax_R1.tick_params(axis='y', labelleft=False, labelright=False)  # Hide y-axis labels
        ax_R1.set_ylabel('')  # Hide y-axis label

        ax_R2.tick_params(axis='both', which='both', length=0)  # Hide ticks
        ax_R2.tick_params(axis='y', labelleft=False, labelright=False)  # Hide y-axis labels
        ax_R2.set_ylabel('')  # Hide y-axis label


        ax.set_xlim(0, 7)

    for ax in axes:
        # Set x tick labels for the top two and bottom two plots
        if ax in [ax_0_0, ax_0_1]:  # Top two plots
            ax.tick_params(axis='x', labeltop=True, labelbottom=False)  # Show x-tick labels at the top, hide at the bottom
        elif ax in [ax_4_0, ax_4_1]:  # Bottom two plots
            ax.tick_params(axis='x', labeltop=False, labelbottom=True)  # Show x-tick labels at the bottom, hide at the top
        else:  # Middle plots
            ax.tick_params(axis='x', labeltop=False, labelbottom=False)  # No x-tick labels (optional)
        # Set x tick lines inside for all plots
        ax.tick_params(axis='x', direction='in', which='both', top=True, bottom=True)  # Make tick lines face inside



    # Explicitly set x-axis labels for the first and last row
    ax_0_0.set_xlabel("Time")  # Top-left subplot
    ax_0_1.set_xlabel("Time")  # Top-right subplot
    ax_4_0.set_xlabel("Time")  # Bottom-left subplot
    ax_4_1.set_xlabel("Time")  # Bottom-right subplot

    # Move top x-axis labels to the top row
    ax_0_0.xaxis.set_label_position("top")
    ax_0_1.xaxis.set_label_position("top")


    # Set y-axis labels for the right column
    ax_0_1.set_ylabel(r"A11 stretch rate $K$", color='black')
    ax_0_1.tick_params(axis='y', labelcolor='black')
    black_label = mlines.Line2D([], [], color='black', label=r"$K_{geom}$", linestyle='dashed')
    blue_label = mlines.Line2D([], [], color='blue', label=r"$K_{mean}$", linestyle='dashed')
    ax_0_1.legend(handles=[black_label, blue_label], loc='upper left', fontsize=10, frameon=False)

    ax_1_1.set_ylabel("A11 average total\nareodynamic strain $a_t$", color='black')
    ax_1_1.tick_params(axis='y', labelcolor='black')

    ax_2_1.set_ylabel("A11 average normal absolute\npropagation velocity $s_a$", color='black')
    ax_2_1.tick_params(axis='y', labelcolor='black')

    ax_3_1.set_ylabel("A11 average density weighed\ndisplacement speed $s_d$", color='black')
    ax_3_1.tick_params(axis='y', labelcolor='black')

    ax_4_1.set_ylabel("Dimentionalisation $d_T/px$", color='black')
    ax_4_1.tick_params(axis='y', labelcolor='black')


    # Move scientific notation from A and iHRR 
    offset_text = ax_0_0.yaxis.get_offset_text()
    offset_text.set_position((-0.08, 0))  # Move offset text to the left side (x=-0.1)

    offset_text = ax_1_0.yaxis.get_offset_text()
    offset_text.set_position((-0.08, 0))  # Move offset text to the left side (x=-0.1)
    
    # Apply subplot adjustments before modifying tick labels
    plt.subplots_adjust(hspace=0)  # This removes the vertical spacing
    plt.tight_layout(rect=[0, 0, 0.95, 1])  # Adjusted rect to provide more space on the right margin
    
    # Hide the minimum tick label for CST cell diameter as the absolute last step
    # Use the directly stored green_axes references
    for i in range(len(green_axes) - 1):  # All but the last one
        axis = green_axes[i]
        # Force drawing the figure to ensure tick labels are created
        plt.draw()
        # Get current tick positions and labels
        ticks = axis.get_yticks()
        # Create new labels with empty first label and consistent formatting
        new_labels = [''] + [f"{tick:.3f}" for tick in ticks[1:]]
        # Apply new labels
        axis.set_yticklabels(new_labels)

    # Save the plot
    plot_filename = os.path.join(output_dir, f'plot_panel_CST.png')
    plt.savefig(plot_filename)
    if show_plot == 1:
        plt.show()
    plt.close(fig)

    print(f"CST Panel plotter finished. Output in {output_dir}")
    return output_dir # Format_1 requires output_dir as first return


# Example usage when script is run directly
if __name__ == "__main__":
    print("Running plotter_3_CPvsA11_CST_Panel as standalone module...")
    
    # Get input directory from user
    input_dir = r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\CIPS_Pipe_Default_dir\20250625_1528537\20250625_1528554\20250625_1626096\20250626_1700136\20250626_1706361"
    
    # Run the plotter function
    output_dir = plotter_3_CPvsA11_CST_Panel(
        input_dir=input_dir,
        cst_expansion_factor=6,
        show_plot=0,
        Plot_log_level=2,
        output_dir_comment=f"CST_Panel_x{6}"
    )

    print(f"\nAnalysis complete! Results saved to: {output_dir}")
