import numpy as np
import matplotlib.pyplot as plt
import warnings
import glob
import os
import pandas as pd
import matplotlib.gridspec as gridspec
import skimage.io as sk_io
from matplotlib.colors import Normalize
import matplotlib as mpl
import Format_1 as F_1
import video_maker_1 as vm1
import matplotlib.cm as cm

# LaTeX settings
plt.rcParams['text.usetex'] = True
LATEX_FONT_SIZE = 16
plt.rcParams['font.size'] = LATEX_FONT_SIZE
plt.rcParams['font.family'] = 'serif'

@F_1.ParameterLog(max_size=1024 * 10)
def plot10_distribution_histogram_3D_only(
    # Input parameters
    input_dir,
    SRec_df=None,
    
    # Distribution parameters
    dist_column='A_cell_SRec_distribution_nonDim2',  # Only 3D distribution
    dist_label='3D Area',
    dist_color='green',
    x_label='Cell Area (Non-Dimensional)',
    plot_title_template='Image {}: {} Distribution',
    
    # Output and display parameters
    output_dir_manual="", 
    output_dir_comment="",
    save_svg=True,
    save_png=True,
    show_plots=False,
    create_video=True,
    video_fps=5,
    
    # Plot appearance parameters
    figure_width=12,
    figure_height=8,
    show_image_inset=True,
    image_inset_size=0.5,
    image_horizontal_position=0.7,
    image_vertical_position=0.6,
    zoom_scale=1.3,
    mask_alpha=0.8,
    show_centroids=True,
    centroid_size=7,
    centroid_alpha=0.6,
    show_info_box=False,
    bin_count=50,
    grid_alpha=0.2,
    Plot_log_level=1,
    x_axis_extension=1.1,
    y_axis_extension=1.1,
    x_axis_limit=None,
    y_axis_limit=None,
    Frequency_percent_of_max=True,
    output_filename_template='Histogram_3D_{:04d}',
    
    # Image selection parameters
    image_numbers=[],
    omit_image_list=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,106],
    CST_cells_only_in_image=False,
    
    # New text and legend customization parameters
    x_label_fontsize=25,
    y_label_fontsize=25,
    title_fontsize=18,
    legend_fontsize=20,
    legend_framealpha=0.5,
    legend_position="upper left",
    legend_bbox_to_anchor=(0, 1),
    tick_label_fontsize=25,
    info_box_fontsize=10,
    mean_line_label_template='$\overline{{d}}_c$ {} = {:.3f}$\delta_T$',
):
    """
    Creates histograms of the 3D distribution from a DataFrame.
    
    This function processes data from a DataFrame, creating histograms for
    the 3D distribution for each row. It can optionally show an inset image of the
    source data with masks and centroids, and can compile the individual plots into a video.
    
    Parameters
    ----------
    input_dir : str
        Path to the directory containing the SRec_DataFrame.pkl file
        with data generated by Spherical_Reconstruction_1.
    SRec_df : pandas.DataFrame or None, optional
        A pre-loaded DataFrame containing the spherical reconstruction data.
        If provided, it overrides loading from the .pkl file in input_dir.
        If None, the function attempts to load SRec_DataFrame.pkl from input_dir.
        Defaults to None.
    output_dir_manual : str, optional
        If provided, specifies the exact output directory path for the plots/video.
        Overrides the default naming convention. Defaults to "".
    output_dir_comment : str, optional
        A comment to append to the default output directory name. Defaults to "".
    save_svg : bool, optional
        If True, saves plots in SVG format. Defaults to True.
    save_png : bool, optional
        If True, saves plots in PNG format. Defaults to True.
    show_plots : bool, optional
        If True, displays plots during execution. Defaults to False.
    create_video : bool, optional
        If True, creates a video from the generated plot images using video_maker_1.
        Defaults to True.
    video_fps : int, optional
        Frames per second for the video if create_video is True. Defaults to 5.
    figure_width : float, optional
        Width of the figure in inches. Defaults to 12.
    figure_height : float, optional
        Height of the figure in inches. Defaults to 9.
    show_image_inset : bool, optional
        If True, shows an inset of the flame image with masks. Defaults to True.
    image_inset_size : float, optional
        Size of the image inset as a fraction of the plot. Defaults to 0.35.
    image_horizontal_position : float, optional
        Horizontal position of the image inset (0-1, where 1 is far right). Defaults to 0.65.
    image_vertical_position : float, optional
        Vertical position of the image inset (0-1, where 1 is top). Defaults to 0.75.
    zoom_scale : float, optional
        Scale factor for zooming in on the spherical flame in the image inset. Defaults to 1.5.
    mask_alpha : float, optional
        Transparency of masks in the inset image. Defaults to 0.3.
    show_centroids : bool, optional
        If True, shows cell centroids in the image inset. Defaults to True.
    centroid_size : int, optional
        Size of the centroid markers in the image inset. Defaults to 10.
    centroid_alpha : float, optional
        Alpha value for the centroid markers in the image inset. Defaults to 0.7.
    show_info_box : bool, optional
        If True, shows the info box with cell count and diameter information on the plot. Defaults to True.
    bin_count : int, optional
        Number of bins for the diameter distribution histogram. Defaults to 30.
    grid_alpha : float, optional
        Transparency of the grid in the plot. Defaults to 0.2.
    Plot_log_level : int, optional
        Controls the verbosity of logging. Defaults to 1.
    x_axis_extension : float, optional
        Factor to extend the x-axis range beyond the min and max area values.
        Defaults to 1.1 (10% extension).
    y_axis_extension : float, optional
        Factor to extend the y-axis range beyond the max frequency value.
        Defaults to 1.1 (10% extension).
    x_axis_limit : tuple or float, optional
        Manual x-axis limit. If a tuple (min, max), sets both limits.
        If a single float, sets only the maximum value. 
        Overrides x_axis_extension if provided.
    y_axis_limit : tuple or float, optional
        Manual y-axis limit. If a tuple (min, max), sets both limits.
        If a single float, sets only the maximum value.
        Overrides y_axis_extension if provided.
    Frequency_percent_of_max : bool, optional
        If True, normalizes frequency as percentage of maximum frequency across all images.
        Default is False.
    output_filename_template : str, optional
        Template for output filenames. Must contain exactly one placeholder '{}' 
        for the image index. Default is 'Histogram_comparison_{:04d}'.
    image_numbers : list, optional
        List of specific image numbers to process. If empty, all images are processed.
        Defaults to [] (process all images).
    omit_image_list : list, optional
        List of image numbers to exclude from processing. Applied after image_numbers filter.
        Defaults to [] (exclude no images).
    CST_cells_only_in_image : bool, optional
        If True, only cells that are included in the CST will be shown in the image inset.
        Requires CST_inclusion column from CST_Selection_1.py. Defaults to False.
    x_label_fontsize : int, optional
        Font size for x-axis label. Defaults to 16.
    y_label_fontsize : int, optional
        Font size for y-axis label. Defaults to 16.
    title_fontsize : int, optional
        Font size for plot title. Defaults to 18.
    legend_fontsize : int, optional
        Font size for legend text. Defaults to 14.
    legend_framealpha : float, optional
        Transparency of the legend box (0-1). Defaults to 0.7.
    legend_position : str, optional
        Position of the legend. Defaults to "upper center".
    legend_bbox_to_anchor : tuple, optional
        Fine-tuning of legend position (x, y). Defaults to (0.5, 0.98).
    tick_label_fontsize : int, optional
        Font size for axis tick labels. Defaults to 12.
    info_box_fontsize : int, optional
        Font size for info box text. Defaults to 10.
    mean_line_label_template : str, optional
        Template for mean value labels. Defaults to 'Mean {}: {:.3f}'.
    
    Returns
    -------
    output_dir : str
        The path to the directory where the output plots and folders are saved.
    
    Notes
    -----
    The function creates separate directories for PNG and SVG outputs within the main output directory.
    It compares original cell diameter distributions with those after spherical reconstruction.
    """
    # Suppress MatplotlibDeprecationWarning if log level is not >= 2
    if Plot_log_level < 2:
        warnings.filterwarnings('ignore', category=mpl.MatplotlibDeprecationWarning)

    #################################################### I/O
    output_dir = F_1.F_out_dir(input_dir, __file__, output_dir_comment=output_dir_comment, 
                            output_dir_manual=output_dir_manual)  # Format_1 required definition of output directory

    # Set normalization option
    normalize_to_percent = True  # Move this declaration up here

    # Create subdirectories for PNG and SVG outputs if needed
    if save_png:
        png_dir = os.path.join(output_dir, "png_plots")
        os.makedirs(png_dir, exist_ok=True)
        print(f"PNG plots will be saved to: {png_dir}") if Plot_log_level >= 1 else None
    
    if save_svg:
        svg_dir = os.path.join(output_dir, "svg_plots")
        os.makedirs(svg_dir, exist_ok=True)
        print(f"SVG plots will be saved to: {svg_dir}") if Plot_log_level >= 1 else None

    #################################################### Load data
    if SRec_df is None:
        # Look for SRec_DataFrame.pkl file
        srec_file_path = os.path.join(input_dir, "SRec_DataFrame.pkl")
        if not os.path.exists(srec_file_path):
            # If not found, try to find any .pkl file
            pkl_files = glob.glob(os.path.join(input_dir, "*.pkl"))
            if pkl_files:
                srec_file_path = pkl_files[0]
            else:
                raise FileNotFoundError(f"No SRec_DataFrame.pkl or other .pkl files found in {input_dir}")
        
        print(f"Loading spherical reconstruction data from: {srec_file_path}") if Plot_log_level >= 1 else None
        SRec_df = pd.read_pickle(srec_file_path)
    else:
        print("Using provided SRec DataFrame") if Plot_log_level >= 1 else None

    # Verify the DataFrame has the required columns
    required_columns = ['d_cell_distribution_nonDim', 'd_cell_SRec_distribution_nonDim', 
                         'image_file_path', 'masks', 'centroid_xIm_distribution_px', 
                         'centroid_yIm_distribution_px', 'A_cell_distribution_nonDim2', 
                         'A_cell_SRec_distribution_nonDim2']
    
    for col in required_columns:
        if col not in SRec_df.columns:
            print(f"Warning: Column '{col}' not found in the DataFrame. Some functionality may be limited.")

    #################################################### Clean data
    # Clean data once after loading
    print("Cleaning data...") if Plot_log_level >= 1 else None
    
    # Create new columns for cleaned data with dynamic names
    dist_clean_column = f'{dist_column}_clean'
    
    SRec_df[dist_clean_column] = SRec_df[dist_column].apply(
        lambda x: x[~np.isnan(x)] if x is not None else np.array([])
    )
    
    # Remove rows where either cleaned array is empty
    valid_rows = SRec_df[dist_clean_column].apply(len) > 0
    SRec_df = SRec_df[valid_rows].reset_index(drop=True)

    if len(SRec_df) == 0:
        print("Error: No valid data found after cleaning") if Plot_log_level >= 0 else None
        return output_dir

    #################################################### Apply image number filtering if specified
    if image_numbers:
        if 'image_number' in SRec_df.columns:
            SRec_df = SRec_df[SRec_df['image_number'].isin(image_numbers)].reset_index(drop=True)
            print(f"Filtered to {len(SRec_df)} images based on specified image numbers") if Plot_log_level >= 1 else None
        else:
            print(f"Warning: image_number column not found in DataFrame, cannot filter by image numbers") if Plot_log_level >= 0 else None
    
    # Exclude images in omit_image_list if provided
    if omit_image_list and 'image_number' in SRec_df.columns:
        SRec_df = SRec_df[~SRec_df['image_number'].isin(omit_image_list)].reset_index(drop=True)
        if Plot_log_level >= 1:
            print(f"Excluded {len(omit_image_list)} images: {omit_image_list}")

    # Verify we have data after filtering
    if len(SRec_df) == 0:
        print("Error: No images to process after filtering") if Plot_log_level >= 0 else None
        return output_dir
        
    #################################################### Calculate global statistics
    # Number of rows in the DataFrame
    N_images = len(SRec_df)
    
    # Concatenate all valid values
    all_dist = np.concatenate(SRec_df[dist_clean_column].values)
    
    # Calculate global min/max
    max_val = np.max(all_dist)
    min_val = np.min(all_dist)
    
    # Calculate global max frequency
    max_frequency_global = 0
    for dist_data in SRec_df[dist_clean_column]:
        hist, _ = np.histogram(dist_data, bins=bin_count)
        max_frequency_global = max(max_frequency_global, np.max(hist))

    print(f"Processing {N_images} images with area range: {min_val:.2f} to {max_val:.2f}") if Plot_log_level >= 1 else None
    print(f"Global maximum frequency: {max_frequency_global}") if Plot_log_level >= 1 else None

    #################################################### Plotting
    # Process each image
    print(f"\nPlotting area distributions:")
    for i in range(N_images):
        print(f"\rProcessing image {i+1}/{N_images}", end='', flush=True) if Plot_log_level >= 1 else None
        
        # Create figure with specified size
        fig = plt.figure(figsize=(figure_width, figure_height))
        ax = fig.add_subplot(111)
        
        # Get the cleaned distributions
        dist_data = SRec_df.iloc[i][dist_clean_column]
        
        # Get the actual image number from the DataFrame (if available)
        image_num = SRec_df.iloc[i]['image_number'] if 'image_number' in SRec_df.columns else i+1
        
        # Create bins for this specific image
        bins = np.linspace(min_val, max_val, bin_count + 1)
        
        # Calculate the histograms
        if Frequency_percent_of_max:
            # Normalize to percentage of total count (instead of % of max)
            total_count = len(dist_data)
            
            # Calculate weights for normalization to percentage of total
            weights = np.ones_like(dist_data) * (100.0 / total_count)
            
            y_label = r'Frequency (\% of total)'
            
            # Plot histograms with normalized values and black edges
            hist = ax.hist(dist_data, bins=bins, alpha=0.6, color=dist_color, 
                   label=r"$d_c$ " + dist_label, weights=weights, edgecolor='black', linewidth=0.5)

            # Calculate actual max frequency for this plot
            this_max_freq = np.max(hist[0])
        else:
            # Use raw counts
            y_label = r'Frequency (count)'
            
            # Plot histograms with raw counts and black edges
            hist = ax.hist(dist_data, bins=bins, alpha=0.6, color=dist_color, 
                   label=dist_label, edgecolor='black', linewidth=0.5)
                   
            # Calculate actual max frequency for this plot
            this_max_freq = np.max(hist[0])
        
        # Set y-axis limit based on user input or actual histogram heights
        if y_axis_limit is not None:
            if isinstance(y_axis_limit, (tuple, list)) and len(y_axis_limit) == 2:
                y_min, y_max = y_axis_limit  # Use both min and max from tuple
            else:
                y_min = 0
                y_max = float(y_axis_limit)  # Use single value as maximum
        else:
            y_min = 0
            y_max = this_max_freq * y_axis_extension
            
        # Add mean area lines with customized labels
        mean_val = np.mean(dist_data)
        ax.axvline(mean_val, color=dist_color, linestyle='--', linewidth=2, 
                  label=mean_line_label_template.format(dist_label, mean_val))
        
        # Set axis limits and labels with customized font sizes
        # Handle x-axis limits similarly to y-axis limits
        if x_axis_limit is not None:
            if isinstance(x_axis_limit, (tuple, list)) and len(x_axis_limit) == 2:
                x_min, x_max = x_axis_limit
            else:
                x_min = min_val * 0.95
                x_max = float(x_axis_limit)
        else:
            x_min = min_val * 0.95
            x_max = max_val * x_axis_extension
        
        ax.set_xlim(x_min, x_max)
        ax.set_ylim(y_min, y_max)
        
        ax.set_xlabel(x_label, fontsize=x_label_fontsize)
        ax.set_ylabel(y_label, fontsize=y_label_fontsize)
        ax.set_title(plot_title_template.format(image_num, dist_label), fontsize=title_fontsize)
        
        # Set tick label font sizes
        ax.tick_params(axis='both', which='major', labelsize=tick_label_fontsize)
        
        # Add grid
        ax.grid(True, alpha=grid_alpha, linestyle='--')
        
        # Add legends with customized appearance
        ax.legend(loc=legend_position, bbox_to_anchor=legend_bbox_to_anchor, 
                 fontsize=legend_fontsize, framealpha=legend_framealpha)

        # Add image inset if requested
        if show_image_inset:
            try:
                # Calculate position based on new parameters
                inset_width = image_inset_size
                inset_height = image_inset_size
                inset_left = image_horizontal_position - (inset_width / 2)
                inset_bottom = image_vertical_position - (inset_height / 2)
                
                # Create inset axes
                ax_inset = fig.add_axes([inset_left, inset_bottom, inset_width, inset_height])
                
                # Load and display image
                image_path = SRec_df.iloc[i]['image_file_path']
                image = sk_io.imread(image_path)
                
                # Make white parts transparent
                if len(image.shape) == 2:  # Grayscale image
                    # Create RGBA image
                    rgba_image = np.zeros((*image.shape, 4), dtype=np.uint8)
                    rgba_image[..., :3] = np.stack([image]*3, axis=-1)
                    rgba_image[..., 3] = np.where(image == 255, 0, 255)
                    image = rgba_image
                elif len(image.shape) == 3:  # RGB image
                    # Create RGBA image
                    rgba_image = np.zeros((*image.shape[:2], 4), dtype=np.uint8)
                    rgba_image[..., :3] = image
                    is_white = np.all(image == 255, axis=-1)
                    rgba_image[..., 3] = np.where(is_white, 0, 255)
                    image = rgba_image

                masks = SRec_df.iloc[i]['masks']
                
                # Filter masks for CST cells only if requested
                if CST_cells_only_in_image and 'CST_inclusion' in SRec_df.columns:
                    # Get the CST inclusion information for this image
                    cst_inclusion = SRec_df.iloc[i]['CST_inclusion']
                    
                    # If it's empty or None, fall back to showing all cells
                    if cst_inclusion is None or len(cst_inclusion) == 0:
                        if Plot_log_level >= 1:
                            print(f"\nWarning: CST_inclusion data not available for image {i+1}, showing all cells")
                    else:
                        # Get cell IDs from the masks
                        cell_ids = np.unique(masks)
                        cell_ids = cell_ids[cell_ids > 0]  # Exclude background
                        
                        # Create a copy of masks with only CST cells
                        cst_masks = np.zeros_like(masks)
                        
                        # Check if we have enough inclusion data for all cells
                        if len(cst_inclusion) >= len(cell_ids):
                            for idx, cell_id in enumerate(cell_ids):
                                if idx < len(cst_inclusion) and cst_inclusion[idx]:
                                    cst_masks[masks == cell_id] = cell_id
                        else:
                            if Plot_log_level >= 1:
                                print(f"\nWarning: CST_inclusion data incomplete for image {i+1}")
                            # Use all masks if inclusion data is incomplete
                            cst_masks = masks
                        
                        # Replace original masks with filtered masks
                        masks = cst_masks
                # Calculate zoom region to focus on the spherical flame
                img_height, img_width = image.shape[:2]
                center_x, center_y = img_width // 2, img_height // 2
                D_SF_px = SRec_df.iloc[i]['D_SF_px']
                zoom_half_size = int(D_SF_px * zoom_scale / 2)
                
                # Ensure zoom region is within image bounds
                left = max(0, center_x - zoom_half_size)
                right = min(img_width, center_x + zoom_half_size)
                top = max(0, center_y - zoom_half_size)
                bottom = min(img_height, center_y + zoom_half_size)
                
                # Extract and display the zoomed region
                image_zoomed = image[top:bottom, left:right]
                ax_inset.imshow(image_zoomed)
                
                # Create a masked array for the masks in the zoomed region
                masks_zoomed = masks[top:bottom, left:right]
                masked_data = np.ma.masked_where(masks_zoomed == 0, masks_zoomed % 10)
                
                # Use older syntax for colormap
                cmap = cm.get_cmap('tab10', 10)
                ax_inset.imshow(masked_data, cmap=cmap, alpha=mask_alpha)

                # Show centroids if requested
                if show_centroids and 'centroid_xIm_distribution_px' in SRec_df.columns:
                    centroids_x = SRec_df.iloc[i]['centroid_xIm_distribution_px']
                    centroids_y = SRec_df.iloc[i]['centroid_yIm_distribution_px']
                    
                    # Filter centroids for CST cells only if requested
                    if CST_cells_only_in_image and 'CST_inclusion' in SRec_df.columns:
                        cst_inclusion = SRec_df.iloc[i]['CST_inclusion']
                        
                        # If we have valid inclusion data, filter centroids
                        if cst_inclusion is not None and len(cst_inclusion) > 0 and len(cst_inclusion) == len(centroids_x):
                            centroids_x = [x for idx, x in enumerate(centroids_x) if cst_inclusion[idx]]
                            centroids_y = [y for idx, y in enumerate(centroids_y) if cst_inclusion[idx]]
                    
                    if len(centroids_x) > 0 and len(centroids_y) > 0:
                        # Adjust centroid coordinates for zoomed view
                        valid_centroids = [(x, y) for x, y in zip(centroids_x, centroids_y)
                                         if left <= x <= right and top <= y <= bottom]
                        if valid_centroids:
                            x_coords, y_coords = zip(*valid_centroids)
                            ax_inset.scatter(
                                [x - left for x in x_coords],
                                [y - top for y in y_coords],
                                c='red', s=centroid_size, alpha=centroid_alpha
                            )

                # Turn off axes for the inset
                ax_inset.axis('off')
                
                # Add a thin border around the inset
                for spine in ax_inset.spines.values():
                    spine.set_visible(True)
                    spine.set_color('black')
                    spine.set_linewidth(0.5)
                
                
            except Exception as e:
                print(f"\nWarning: Could not display image inset for image {i+1}: {str(e)}") if Plot_log_level >= 1 else None
        
        # Add cell count and diameter info in a separate box with customized font size
        if show_info_box:
            try:
                d_3d = np.mean(SRec_df.iloc[i]['d_cell_SRec_distribution_nonDim'])
                diameter_str = fr"3D Diameter = {d_3d:.2f}$\delta_T$"
                cell_count = len(dist_data)
                box_text = f"Cell count: {cell_count}\n{diameter_str}"
                ax.text(0.02, 0.88, box_text, 
                       transform=ax.transAxes, fontsize=info_box_fontsize,
                       bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))
            except Exception as e:
                print(f"\nWarning: Could not add diameter info: {str(e)}") if Plot_log_level >= 1 else None

        # Save plots with configurable filename - use actual image number
        # Convert image_num to int to avoid format errors with float values
        try:
            image_num_int = int(image_num)
        except (ValueError, TypeError):
            image_num_int = i + 1  # Fallback to loop index if conversion fails
        
        base_filename = output_filename_template.format(image_num_int)
        
        if save_png:
            png_path = os.path.join(png_dir, f'{base_filename}.png')
            plt.savefig(png_path, dpi=300, bbox_inches='tight')
        
        if save_svg:
            svg_path = os.path.join(svg_dir, f'{base_filename}.svg')
            plt.savefig(svg_path, format='svg', bbox_inches='tight')
        
        if show_plots:
            plt.show()
        
        plt.close(fig)
    
    # End of processing message
    print("\nFinished processing all images") if Plot_log_level >= 1 else None
    
    # Create video if requested
    if create_video and save_png:
        print("Creating video from plots...") if Plot_log_level >= 1 else None
        try:
            vm1.create_video_from_images(
                plot_image_folder=png_dir,
                video_output_dir=output_dir,
                fps=video_fps,
            )
            print(f"Video created in {output_dir}") if Plot_log_level >= 1 else None
        except Exception as e:
            print(f"Error creating video: {str(e)}") if Plot_log_level >= 0 else None
    
    return output_dir

# Example usage
if __name__ == "__main__":
    print("Running 3D-Only Distribution Histogram Plotter...")
    plot10_distribution_histogram_3D_only(
        input_dir=r"C:\Users\obs\OneDrive\ETH\ETH_MSc\Masters Thesis\CIPS_Pipe_Default_dir\20250625_1528537\20250625_1528554\20250625_1626096\20250626_1700136\20250628_2007187",
        output_dir_comment="3D Only Diameter Distribution",
        image_numbers=[49,103,129,135],
        y_axis_limit=25,
        dist_column='d_cell_SRec_distribution_nonDim',
        dist_label='3D',
        dist_color='green',
        x_label=r'$d_c$ / $\delta_T$',
        plot_title_template='',
        output_filename_template='Diameter_3D_only_histogram_{:04d}',
        save_svg=True,
        save_png=True,
        show_plots=False,
        create_video=True,
        show_image_inset=True,
        CST_cells_only_in_image=True,
        Plot_log_level=1
    )